blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/md-shakib-khan/portfolio/discussions
    about: Need help self hosting or ask a general question about the project? Open a discussion